=== m-marini/leibnitz/leibnitz/leibnitz-lib/src/main/resources/leibnitz-2-0-0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.mmarini.org/leibnitz-2-0-0"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:l="http://www.mmarini.org/leibnitz-2-0-0">
	<annotation>
		<documentation>
		</documentation>
	</annotation>
	<element name="definitions" type="l:DefinitionsType"></element>
	<complexType name="DefinitionsType">
		<sequence>
			<choice maxOccurs="unbounded" minOccurs="0">
				<element ref="l:variable"></element>
				<element ref="l:function"></element>
			</choice>
			<element ref="l:update" maxOccurs="unbounded"
				minOccurs="0">
			</element>
			<element ref="l:corpe" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>
	<complexType name="FunctionType">
		<simpleContent>
			<extension base="string">
				<attribute name="id" type="l:IdType" use="required"></attribute>
			</extension>
		</simpleContent>
	</complexType>
	<simpleType name="IdType">
		<restriction base="string">
			<whiteSpace value="collapse"></whiteSpace>
		</restriction>
	</simpleType>	<element name="variable" type="l:FunctionType"></element>
	<element name="function" type="l:FunctionType"></element>
	<element name="update" type="l:FunctionType"></element>
    <element name="corpe" type="l:CorpeType"></element>
    <complexType name="CorpeType">
    	<sequence></sequence>
    	<attribute name="location" type="l:IdType" use="required"></attribute>
    	<attribute name="rotation" type="l:IdType"></attribute>
    </complexType>
</schema>

=== m-marini/leibnitz/leibnitz/leibnitz-3d/src/samples/corpi.xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.mmarini.org/leibnitz-2-0-0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mmarini.org/leibnitz-2-0-0 ../../../leibnitz-lib/src/main/resources/leibnitz-2-0-0.xsd ">
	<function id="dt">10e-3</function>
	<variable id="t">0</variable>
	<function id="w1">2 * PI</function>
	<function id="a1">t * w1</function>
	<function id="xr1">e0 + 0 * e2</function>
	<function id="yr1">e1 + 0 * e2</function>
	<function id="A">xr1 * sin(a1) + yr1 * cos(a1)</function>

	<function id="w2">2 * PI / 10</function>
	<function id="a2">t * w2</function>
	<function id="xr2">2*e0 + 0 * e2</function>
	<function id="yr2">1 * e2</function>
	<function id="B">xr2 * sin(a2) + yr2 * cos(a2)</function>

	<function id="w3">2 * PI / 7</function>
	<function id="a3">t * w3</function>
	<function id="xr3">2*e1 + 0 * e2</function>
	<function id="yr3">1 * e2</function>
	<function id="C">xr3 * sin(a3) + yr3 * cos(a3)</function>

	<update id="t">t + dt</update>
	<corpe location="A" />
	<corpe location="B" />
	<corpe location="C" />
</definitions>

=== m-marini/leibnitz/leibnitz/leibnitz-3d/src/bin/newton.xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.mmarini.org/leibnitz-2-0-0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mmarini.org/leibnitz-2-0-0 ../../../leibnitz-lib/src/main/resources/leibnitz-2-0-0.xsd ">
	<function id="dt">0.01</function>
	<function id="m1">100</function>
	<function id="m2">300</function>
	<function id="K">10e-3</function>
	<function id="v">0.5</function>
	<function id="vv">e0+0*e1+e2</function>
	
	
	<variable id="P1">1 * e0 + 0 * e1 + 0 * e2</variable>
	<variable id="P2">-1 * e0 + 0 * e1 + 0 * e2</variable>
	<variable id="V1">v * n(vv)</variable>
	<variable id="V2">v * n(-vv)</variable>

	<function id="G12">K * n(P2 - P1) / tr(P2 - P1)</function>
	<function id="A1">m2 * G12</function>
	<function id="A2">-m1 * G12</function>

	<update id="V1">V1 + A1 * dt</update>
	<update id="V2">V2 + A2 * dt</update>
	<update id="P1">P1 + V1 * dt</update>
	<update id="P2">P2 + V2 * dt</update>

	<corpe location="P1" />
	<corpe location="P2" />
</definitions>

=== m-marini/leibnitz/leibnitz-3d/src/samples/paraboloid.xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.mmarini.org/leibnitz-2-0-0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mmarini.org/leibnitz-2-0-0 ../../../leibnitz-lib/src/main/resources/leibnitz-2-0-0.xsd ">

	<function id="dt">1e-3</function>

	<function id="a">-0.5</function>
	<function id="g">9.81</function>

	<function id="q1_0">1</function>
	<function id="q2_0">0</function>

	<function id="qv1_0">0</function>
	<function id="qv2_0">sqrt(-2*a*g)*1.5</function>

	<function id="b0">(e0 + 0 * e1)</function>
	<function id="b1">e1</function>

	<variable id="q">q1_0 * e0 + q2_0 * e1</variable>
	<variable id="qv">qv1_0 * e0 + qv2_0 * e1</variable>

	<function id="q1">q * b0</function>
	<function id="q2">q * b1</function>

	<function id="qv1">qv * b0</function>
	<function id="qv2">qv * b1</function>

	<function id="qa2">-2 * qv1 * qv2 / q1</function>
	<function id="qa1">q1 * (2 * a * g - 4 * qv1^2 * a^2 + qv2^2) / (4 * q1^2 * a^2 + 1)</function>

	<function id="qa">qa1 * e0 + qa2 * e1</function>

	<function id="x">q1 * cos(q2)</function>
	<function id="z">-q1^2 * a</function>
	<function id="y">q1 * sin(q2)</function>
	<function id="r">x * e0 + y * e1 + z * e2</function>
	<function id="r0">0 * e2</function>

	<update id="qv">qv + qa * dt</update>
	<update id="q">q + qv * dt</update>

	<corpe location="r" />
	<corpe location="r0" />
</definitions>

=== m-marini/leibnitz/leibnitz/leibnitz-3d/src/samples/newton.xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.mmarini.org/leibnitz-2-0-0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mmarini.org/leibnitz-2-0-0 ../../../leibnitz-lib/src/main/resources/leibnitz-2-0-0.xsd ">
	<function id="dt">0.01</function>
	<function id="m1">100</function>
	<function id="m2">300</function>
	<function id="K">10e-3</function>
	<function id="v">1</function>
	<function id="r">1</function>
	<function id="R">e0 + 0 * e2</function>
	<function id="V">e2</function>

	<variable id="R1">r * n(R)</variable>
	<variable id="V1">v * n(V)</variable>

	<function id="Q1">m1 * V1</function>
	<function id="Q2">-Q1</function>

	<function id="M">m1 * r</function>

	<variable id="R2">-n(R1) * M / m2</variable>
	<variable id="V2">Q2 /m2</variable>

	<function id="R12">R2 - R1</function>
	<function id="A1">n(R12) * K * m2 / tr(R12)</function>
	<function id="A2">-n(R12) * K * m1 / tr(R12)</function>

	<update id="V1">V1 + A1 * dt</update>
	<update id="V2">V2 + A2 * dt</update>
	<update id="R1">R1 + V1 * dt</update>
	<update id="R2">R2 + V2 * dt</update>

	<corpe location="R1" />
	<corpe location="R2" />
</definitions>
